apiVersion: v1
kind: Service
metadata:
  name: news-sentinel-api
  namespace: news-sentinel
spec:
  type: NodePort
  selector:
    app: news-sentinel-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
